#!/bin/sh

# Wait a moment to ensure database volume is fully mounted
sleep 2

# This script is run inside the Docker container to apply any new database migrations before starting the app
echo "Running migrations..."
bunx drizzle-kit push --config=drizzle.config.ts

echo "Starting Next.js..."
# Use node to run the server.js generated by next build standalone
exec bun run server.js
